version: '3.3'

# docker push registry.gitlab.com/coronavirus-outbreak-control/covid-19-consumer-server
services:

  doctor-app-server-base:
    image: doctor-app-server-base
    build:
      context: .
      dockerfile: docker/doctor-app-server-base/Dockerfile

  doctor-app-server:
    image: registry.gitlab.com/coronavirus-outbreak-control/covid-19-doctor-server
    build:
      context: .
      dockerfile: docker/covid19-doctor-server/Dockerfile
      args:
        _env: ${_env}